assert_throws.burn:
	assert.throws( function() {
		print "a"
		3 + "3"
		print "b"
	}, TypeError )

$ $BURN assert_throws.burn
	* stdout
		a

throws_wrong_type.burn:
	try {
		assert.throws( function() {}, Integer )
	} catch AssertionError $e {
		print "AssertionError"
	}

$ $BURN throws_wrong_type.burn
	* stdout
		AssertionError
